### ISSUE TITLE
这个sdk支持付款码支付吗？

### ISSUE THREAD

**Issue by seacoastboy** [godcong/wego#5]
没发现在哪里配置使用付款码支付，

**Comment by godcong** [comment]
按照微信给的流程有两种实现方式：
模式一:
1：设置微信扫码回调地址
2：添加监听HandleScannedNotify
3：调用payment的Scheme接口生成二维码地址，用户扫码交易
4：触发HandleScannedNotify，在监听中调用统一下单API(提前设置好HandlePaidNotify监听地址)
5：返回带有prepay_id的Map
6：支付成功触发HandlePaidNotify

模式二：
1：添加监听HandlePaidNotify
2：先调用统一下单API，返回二维码地址（这个二维码地址比较简单，生成的二维码会比较容易被扫码）
3：支付成功触发HandlePaidNotify

具体流程可以参考下官方文档：
https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_1

另：请使用tag版本，master正在进行功能和性能的优化，目前仅小部分功能测试通过

**Comment by seacoastboy** [comment]
付款码支付流程是如下流程：
https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=5_1
付款码支付是手机打开收付款后，直接对准扫描器或扫描盒子进行扫描支付， 支付类型是micropay

**Comment by seacoastboy** [comment]
有交流群吗？

**Comment by godcong** [comment]
Payment直接有个Pay方法对应的是/pay/micropay
其他回调流程都是一样的

暂时还没交流群,这是个好想法.可以考虑

**Comment by seacoastboy** [comment]
好的， 我测试看看， 可以考虑使用微信， 这样可以找人完善文档
